// app-vue/src/components/Header.vue
<template>
  <header class="header">
    <nav>
      <a href="#">Blog</a>
      <a href="#">Sobre</a>
      <a href="#">Descrição</a>
    </nav>
  </header>
</template>

<style scoped>
.header {
  background-color: #2f5c8f;
  padding: 20px;
}

nav {
  display: flex;
  justify-content: center;
  gap: 20px;
}

a {
  color: white;
  text-decoration: none;
}
</style>

// proj-react-02/src/components/Header.jsx
const Header = () => {
  return (
    <header style={styles.header}>
      <nav style={styles.nav}>
        <a href="#">Blog</a>
        <a href="#">Sobre</a>
        <a href="#">Descrição</a>
      </nav>
    </header>
  );
};

const styles = {
  header: {
    backgroundColor: "#2f5c8f",
    padding: "20px"
  },
  nav: {
    display: "flex",
    gap: "20px",
    justifyContent: "center"
  }
};

export default Header;
