// app-vue/src/components/Hero.vue
<template>
  <section class="hero">
    <img src="https://i.imgur.com/0y8Ftya.png" />
    <div>
      <h1>Halina Amorim</h1>
      <p>
        Graduada em Engenharia Ambiental e Sanitária, Pedagoga e estudante em Análise e 
         Desenvolvimento de Sistemas e Técnico em Informática. E sempre em busca de novos conhecimentos.
      </p>
    </div>
  </section>
</template>

<style scoped>
.hero {
  background-color: #2f5c8f;
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 20px;
  padding: 40px;
}

img {
  width: 120px;
  border-radius: 50%;
}
</style>

// proj-react-02/src/components/Hero.jsx
const Hero = () => {
  return (
    <section style={styles.hero}>
      <img
        src="https://i.imgur.com/0y8Ftya.png"
        alt="Perfil"
        style={styles.image}
      />
      <div>
        <h1>Halina Amorim</h1>
        <p>
          Graduada em Engenharia Ambiental e Sanitária, Pedagoga e estudante em Análise e 
         Desenvolvimento de Sistemas e Técnico em Informática. E sempre em busca de novos conhecimentos.
        </p>
      </div>
    </section>
  );
};

const styles = {
  hero: {
    backgroundColor: "#2f5c8f",
    color: "white",
    display: "flex",
    alignItems: "center",
    gap: "20px",
    padding: "40px",
    justifyContent: "center"
  },
  image: {
    width: "120px",
    borderRadius: "50%"
  }
};

export default Hero;
